Repository mlsystemdesignproject/neighbourhood-safety-prediction, pull requests merged in 2023-09, with the labels that each got.

#12 minor grammar correction
  assumptions_ru.md
Labels: documentation

#17 adding more files for exploration, and initial look
  data/MPS/MPS Borough Level Crime (Historical).csv
  data/MPS/MPS Borough Level Crime (most recent 24 months).csv
  data/MPS/offence-group-classification-june-2022.xlsx
  notebooks/Data_exploration_borough.ipynb
  notebooks/your_report.html
Labels: data

#20 add lines to gitignore
  .gitignore
Labels: good first issue

#22 EDA#7 - adding area codes, merging all datasets, minor corrections
  notebooks/Data_exploration_borough.ipynb
Labels: data

#23 Alex streamlit draft
  data/london-map/London_Borough_Excluding_MHW.GSS_CODE.atx
  data/london-map/London_Borough_Excluding_MHW.NAME.atx
  data/london-map/London_Borough_Excluding_MHW.dbf
  data/london-map/London_Borough_Excluding_MHW.shp
  data/london-map/London_Borough_Excluding_MHW.shx
  requirements.txt
  service/london-map.py
Labels: enhancement

#15 add first assumptions for Methodology section
  designdoc/ml_system_design_doc.md
Labels: documentation, enhancement

#37 Alex explore mps use force data
  data/MPS_actions/use_force/UF_aggregated_22_23.csv
  models/dummy_prophet_model_01.joblib
  notebooks/alex_1_use_force.ipynb
  notebooks/alex_2_prophet_UF_model.ipynb
Labels: enhancement
